---
title: "Artificial Intelligence in Measurement and Education"
 
format: 
  revealjs:
    logo: ../../images/logo-no-background-name.png
    theme: [default, aime_theme.scss]
---

## Introductions

### Executive Board

-   Co-Chair: Chris Ormerod

-   Co-chair: John Whitmer

-   Secretary: Maggie Beiting-Parrish

## Outline

-   AIME Updates

-   Research Presentation: Ikkyu Choi, ETS

-   Additional SIG Updates & Calls for Participation

## AIME Updates

---

## AIME-Con 2.0 Updates 

* Submitted a proposal to the NCME Board for AIME-Con 2.0 

* Tentative timeline - late Fall 2026 

* Waiting on board decision and bids around venues 

* Welcome any suggestions or ideas people have in the meantime 

* Please contact Maggie, Chris, or Josh 

---

## Journal of Educational Measurement - Special Issue 

* Based on the AIME-Con Proceedings 

* A special issue of JEM 

* Tentative timeline - publishing in September/October 2026 

* Needs 30% new information to be published 

* Will start emailing in the next few weeks, but will also take volunteers 

* Please contact Maggie, Chris, or Josh if you want your paper to be included 


---

## Research Presentation

Ikkyu Choi, ETS

When Language Models Model Items and Examinees: Methodological Considerations for Evaluation

# Additional SIG Updates & Calls for Participation

---

## Special Issue: The Asia-Pacific Education Researcher 

* **Topic:** Review and Meta-Analysis of AI in Education 

*  **Focus:** The special issue will focus on a comprehensive review and meta-analysis of how artificial intelligence (AI) impacts education, spanning multiple critical areas that address both current challenges and future opportunities. 


*  **Goal:** This issue aims to foster transformative impacts in education through AI, employing a review-centric approach that synthesizes existing research, identifies gaps in our understanding, and suggests theoretical and practical paths forward. 


* **Key Dates:**
* Full paper submission deadline: 30 March 2026 

* Review decision: 1 June 2026 

* Final version submission: 15th September 2026 

* Publication date: 15 October 2026 


*  **Website:** [https://link.springer.com/collections/daaajbgbgq](https://link.springer.com/collections/daaajbgbgq) 



---

### Special Issue: Journal of Technology - Integrated Lessons & Teaching 

*  **Topic:** Special issue regarding artificial intelligence in education 

*  **Due:** End of January 2026 

*  **Tentative Publication date:** June 2026 

*  **Website:** [https://journals.uwyo.edu/index.php/jtilt/announcement/view/51](https://journals.uwyo.edu/index.php/jtilt/announcement/view/51) 



## International Meeting of the Psychometric Society

IMPS is the annual International Meeting of the Psychometric Society, a professional organization devoted to the development of psychology as a quantitative rational science, including the advancement of theory and methodology for behavioral data analysis in psychology, education, and the social and behavioral sciences generally.

The IMPS 2026 Annual Meeting is scheduled to be an in-person meeting. The conference will take place at Yonsei University. Mark your calendars to join us in Seoul, Republic of Korea, in July 2026, and please continue to check this website in the future for more updates!

**Proposal Deadline**: January 15, 2026

**Place**: Seoul, Republic of Korea

**Date**: July 21-24, 2026

https://www.psychometricsociety.org/

## The 27th International Conference on AI in Education (AIED 2026)

AIED 2026 marks the 27th edition of the International Conference on Artificial Intelligence in Education, at a time when AI is transforming education and society at an unprecedented pace. AIED 2026 will serve as a vibrant forum for researchers, practitioners, and policymakers to critically examine the promises, challenges, and impacts of AI in education.

**Proposal Deadline**: January 26, 2026

**Place**: Seoul, Republic of Korea

**Date**: June 29 - July 3, 2026
